# Model
model:
  in_dim: 10
  out_dim: 3          # 3 action: buy, sell, hold
  lstm:
    hidden: 64        # размер скрытого состояния LSTM
    layers: 1         # число слоёв
  actor:
    h1: 128           # h1: first hidden layer
    h2: 64
  critic:
    h1: 128
    h2: 64

# Environment
env:
  name: TradingEnv
  window_size: 60
  initial_balance: 5000
  position_size: 0.6
  episode_len: 90
  fee: 0.05
  stop_loss: 300
  take_profit: 1000
  test:
    position_size: 2

# collector
collector:
  frames_per_batch: 5000
  total_frames: 2000000

# Optim
optim:
  lr: 0.0005
  steps_per_batch: 5
  eps: 1.0e-5
  weight_decay: 1e-4
  max_grad_norm: 1.0
#  num_epochs: 10       # optimization steps per batch of data collected
  anneal_lr: True

# loss
loss:
  gamma: 0.98
  gae_lambda: 0.95
  clip_epsilon: 0.05
  anneal_clip_epsilon: True
  critic_coef: 1.0
  entropy_coef: 0.03
  loss_critic_type: smooth_l1 # l2

# log file
log:
  pos_log: log/env_pos_log.csv
  episode_log: log/env_episode_log.csv
  test_pos_log: log/test/env_pos_log.csv
  test_episode_log: log/test/env_episode_log.csv

# Test
test:
  checkpoint_path: checkpoints/model_checkpoint_0606_214146.pth

  # model_checkpoint_0514_191208.pth   #model_checkpoint_0514_173917.pth  # model_checkpoint_0510_115131.pth  # 1d   # model_checkpoint_0510_145359.pth  # 30m

