# Model
model:
  in_dim: 13
  out_dim: 3   # 3 action: buy, sell, hold
  actor:
    h1: 256    # h1: first hidden layer
    h2: 128
  critic:
    h1: 256
    h2: 128

# Environment
env:
  name: TradingEnv
  initial_balance: 10000
  position_size: 0.05
  episode_len: 200
  fee: 0.1
  nums: 1

# collector
collector:
  frames_per_batch: 8000
  total_frames: 3500000

# Optim
optim:
  lr: 0.0005
  steps_per_batch: 6
  eps: 1.0e-5
  weight_decay: 0.0
  max_grad_norm: 1.0
#  num_epochs: 10       # optimization steps per batch of data collected
  anneal_lr: True

# loss
loss:
  gamma: 0.98
  gae_lambda: 0.95
  clip_epsilon: 0.05
  anneal_clip_epsilon: True
  critic_coef: 1.0
  entropy_coef: 0.04
  loss_critic_type: smooth_l1 # l2

# log file
log:
  pos_log: log/env_pos_log.csv
  episode_log: log/env_episode_log.csv
  test_pos_log: log/test/env_pos_log.csv
  test_episode_log: log/test/env_episode_log.csv

test:
  checkpoint_path: checkpoints/model_checkpoint_0506_095649.pth  #model_checkpoint_0506_000122.pth  #model_checkpoint_0505_200525.pth

